### ISSUE TITLE
When student attempts to view grades: Undefined index: released

### ISSUE THREAD

**Issue by garykc** [jflexlanoue/CS490#72] opened 2016-08-06 19:04 UTC
[see](http://imagizer.imageshack.com/img921/7930/zZOUPU.png)

**Comment by GeorgeHahn** [comment] 2016-08-07 00:40
This is a duplicate of https://github.com/jflexlanoue/CS490/issues/64

On Sat, Aug 6, 2016 at 3:04 PM -0400, "garykc" notifications@github.com wrote:

see

**Closed as completed** 2016-08-09 03:22 UTC
